def make_default_state():
  from board import Cell
  from piece import Piece
  return [
    [
      Cell(Piece("r", "b", (0, 0)), "w"),
      Cell(Piece("n", "b", (0, 1)), "b"),
      Cell(Piece("b", "b", (0, 2)), "w"),
      Cell(Piece("q", "b", (0, 3)), "b"),
      Cell(Piece("k", "b", (0, 4)), "w"),
      Cell(Piece("b", "b", (0, 5)), "b"),
      Cell(Piece("n", "b", (0, 6)), "w"),
      Cell(Piece("r", "b", (0, 7)), "b"),
    ],
    [
      Cell(Piece("p", "b", (1, 0)), "b"),
      Cell(Piece("p", "b", (1, 1)), "w"),
      Cell(Piece("p", "b", (1, 2)), "b"),
      Cell(Piece("p", "b", (1, 3)), "w"),
      Cell(Piece("p", "b", (1, 4)), "b"),
      Cell(Piece("p", "b", (1, 5)), "w"),
      Cell(Piece("p", "b", (1, 6)), "b"),
      Cell(Piece("p", "b", (1, 7)), "w"),
    ],
    [
      Cell(None, "w"),
      Cell(None, "b"),
      Cell(None, "w"),
      Cell(None, "b"),
      Cell(None, "w"),
      Cell(None, "b"),
      Cell(None, "w"),
      Cell(None, "b"),
    ],
    [
      Cell(None, "b"),
      Cell(None, "w"),
      Cell(None, "b"),
      Cell(None, "w"),
      Cell(None, "b"),
      Cell(None, "w"),
      Cell(None, "b"),
      Cell(None, "w"),
    ],
    [
      Cell(None, "w"),
      Cell(None, "b"),
      Cell(None, "w"),
      Cell(None, "b"),
      Cell(None, "w"),
      Cell(None, "b"),
      Cell(None, "w"),
      Cell(None, "b"),
    ],
    [
      Cell(None, "b"),
      Cell(None, "w"),
      Cell(None, "b"),
      Cell(None, "w"),
      Cell(None, "b"),
      Cell(None, "w"),
      Cell(None, "b"),
      Cell(None, "w"),
    ],
    [
      Cell(Piece("p", "w", (6, 0)), "w"),
      Cell(Piece("p", "w", (6, 1)), "b"),
      Cell(Piece("p", "w", (6, 2)), "w"),
      Cell(Piece("p", "w", (6, 3)), "b"),
      Cell(Piece("p", "w", (6, 4)), "w"),
      Cell(Piece("p", "w", (6, 5)), "b"),
      Cell(Piece("p", "w", (6, 6)), "w"),
      Cell(Piece("p", "w", (6, 7)), "b"),
    ],
    [
      Cell(Piece("r", "w", (7, 0)), "b"),
      Cell(Piece("n", "w", (7, 1)), "w"),
      Cell(Piece("b", "w", (7, 2)), "b"),
      Cell(Piece("q", "w", (7, 3)), "w"),
      Cell(Piece("k", "w", (7, 4)), "b"),
      Cell(Piece("b", "w", (7, 5)), "w"),
      Cell(Piece("n", "w", (7, 6)), "b"),
      Cell(Piece("r", "w", (7, 7)), "w"),
    ],
  ]
